title: "Idea: "
labels:
  - idea
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing an idea for Moody.
        This space is for brainstorming and early feedback.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this idea solve?
      placeholder: Describe the problem you are facing.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Idea
      description: Describe your idea or improvement.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any screenshots, links, or references?
